# Generated by Django 6.1 on 2026-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("value", models.BinaryField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="django_gesu_expires_b1953b_idx")],
            },
        ),
    ]
